# -*- coding: utf-8 -*-
"""Generate text using GPT2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DGonJHfYX55Thu5WqI9UFPvCWADUsniz
"""

from transformers import pipeline

import gradio as gr

generator = pipeline("text-generation", model="gpt2")

"""##### https://www.gradio.app/docs/gradio/introduction

"""

# 🧠 Generative AI Interactive App using Gradio
# ------------------------------------------------
# Experiment with how Temperature affects creativity in text generation.
# Lower values → logical and precise text.
# Higher values → more creative and unpredictable text.
# 🧩 Text generation function
def gen_ai(prompt, temperature, max_length):
    """
    Generate text using GPT2.
    Args:
        prompt (str): The input text prompt.
        temperature (float): Creativity level (0=logical, 1=very creative).
        max_length (int): Maximum number of tokens in the output.
    """
    try:
        result = generator(
            prompt,
            max_length=int(max_length),
            temperature=float(temperature),
            top_p=0.9,
            num_return_sequences=1,
            repetition_penalty=1.2,
            do_sample=True,
            pad_token_id=50256
        )
        return result[0]["generated_text"]
    except Exception as e:
        return f"⚠️ Error while generating text: {e}"

# 🖥️ Gradio Interface
demo = gr.Interface(
    fn=gen_ai,
    inputs=[
        gr.Textbox(
            label="📝 Enter your Prompt",
            lines=2,
            placeholder="e.g. The future of artificial intelligence will transform education because"
        ),
        gr.Slider(
            minimum=0.1,
            maximum=1.0,
            value=0.7,
            step=0.1,
            label="🎛 Temperature (Creativity Control)",
            info=(
                "Lower = more logical and predictable (0.2–0.4)\n"
                "Balanced = mix of logic and creativity (0.5–0.7)\n"
                "Higher = more creative and random (0.8–1.0)"
            )
        ),
        gr.Slider(
            minimum=50,
            maximum=300,
            value=100,
            step=10,
            label="📏 Max Length (Output Tokens)"
        )
    ],
    outputs=gr.Textbox(
        label="Generated Text",
        lines=12,
        placeholder="Your generated text will appear here..."
    ),
    title="Generative AI Text Generator (GPT2)",
    description=(
        "Type a short prompt and watch the model continue your text. "
        "Adjust the Temperature to explore how creativity changes the response."
    ),
    theme="soft",
    examples=[
        ["The future of artificial intelligence will transform education because", 0.3, 100],
        ["The future of artificial intelligence will transform education because", 0.7, 100],
        ["The future of artificial intelligence will transform education because", 0.95, 100]
    ]
)

# Launch the app
if __name__ == "__main__":
    demo.launch()

